insert into JobCategories values( 'Accounting/Finance','Accountant')
insert into JobCategories values( 'Accounting/Finance','Director Of Finance')
insert into JobCategories values( 'Accounting/Finance','Office Manager Bookkeeper')
insert into JobCategories values( 'Accounting/Finance','Accounting Assistant')
insert into JobCategories values( 'Accounting/Finance','Finance Manager')
insert into JobCategories values( 'Accounting/Finance','Quantitative Analyst')
insert into JobCategories values( 'Accounting/Finance','Accounting Clerk')
insert into JobCategories values( 'Accounting/Finance','Financial Advisor')
insert into JobCategories values( 'Accounting/Finance','Quantitative Research Analyst')
insert into JobCategories values( 'Accounting/Finance','Accounting Manager')
insert into JobCategories values( 'Accounting/Finance','Financial Analyst')
insert into JobCategories values( 'Accounting/Finance','Senior Accountant')
insert into JobCategories values( 'Accounting/Finance','Assistant Controller')
insert into JobCategories values( 'Accounting/Finance','Financial Associate')
insert into JobCategories values( 'Accounting/Finance','Tax Accountant')
insert into JobCategories values( 'Accounting/Finance','Billing Specialist')
insert into JobCategories values( 'Accounting/Finance','Financial Reporting Manager')
insert into JobCategories values( 'Accounting/Finance','Tax Manager')
insert into JobCategories values( 'Accounting/Finance','Bookkeeper')
insert into JobCategories values( 'Accounting/Finance','Full Charge Bookkeeper')
insert into JobCategories values( 'Accounting/Finance','Treasury Analyst')
insert into JobCategories values( 'Accounting/Finance','Budget Analyst')
insert into JobCategories values( 'Accounting/Finance','General Ledger Accountant')
insert into JobCategories values( 'Accounting/Finance','VP Director of Finance')
insert into JobCategories values( 'Accounting/Finance','CNA')
insert into JobCategories values( 'Accounting/Finance','Internal Auditor')
insert into JobCategories values( 'Accounting/Finance','VP of Finance')
insert into JobCategories values( 'Accounting/Finance','Controller')
insert into JobCategories values( 'Accounting/Finance','Night Auditor')
insert into JobCategories values( 'Accounting/Finance','WFF USC Credit Manager')

insert into JobCategories values( 'Healthcare','Case Manager')
insert into JobCategories values( 'Healthcare','Medical Worker')
insert into JobCategories values( 'Healthcare','Phlebotomist')
insert into JobCategories values( 'Healthcare','Dental Assistant')
insert into JobCategories values( 'Healthcare','Nuclear Medicine Technologist')
insert into JobCategories values( 'Healthcare','Physical Therapist')
insert into JobCategories values( 'Healthcare','Dental Hygienist')
insert into JobCategories values( 'Healthcare','Nurse')
insert into JobCategories values( 'Healthcare','Physician Assistant')
insert into JobCategories values( 'Healthcare','Director of Nursing')
insert into JobCategories values( 'Healthcare','Nurse Assistant')
insert into JobCategories values( 'Healthcare','Respiratory Therapist')
insert into JobCategories values( 'Healthcare','Health Unit Coordinator')
insert into JobCategories values( 'Healthcare','Nurse LVN')
insert into JobCategories values( 'Healthcare','Social Worker')
insert into JobCategories values( 'Healthcare','Home Health Aide')
insert into JobCategories values( 'Healthcare','Nurse Practitioner')
insert into JobCategories values( 'Healthcare','Unit Clerk')
insert into JobCategories values( 'Healthcare','Massage Therapist')
insert into JobCategories values( 'Healthcare','Nurse RN')
insert into JobCategories values( 'Healthcare','Unit Secretary')
insert into JobCategories values( 'Healthcare','Medical Assistant')
insert into JobCategories values( 'Healthcare','Nursing Assistant')
insert into JobCategories values( 'Healthcare','Veterinary Receptionist')
insert into JobCategories values( 'Healthcare','Medical Receptionist')
insert into JobCategories values( 'Healthcare','Nutritionist')
insert into JobCategories values( 'Healthcare','Veterinary Technician')
insert into JobCategories values( 'Healthcare','Medical Technologist')
insert into JobCategories values( 'Healthcare','Occupational Therapist')
insert into JobCategories values( 'Healthcare','Vocational Rehabilitation Counselor')

insert into JobCategories values( 'Non-Profit/Volunteering','Community Volunteer')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Care Specialist')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Leader')
insert into JobCategories values( 'Non-Profit/Volunteering','Red Cross')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Care Worker')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Program Coordinator')
insert into JobCategories values( 'Non-Profit/Volunteering','Special Events Coordinator')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Coordinator')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Program Director')
insert into JobCategories values( 'Non-Profit/Volunteering','Volunteer Coordinator')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Counselor')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Specialist')
insert into JobCategories values( 'Non-Profit/Volunteering','Volunteer Recruiter')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Development Manager')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Worker')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Advocate')
insert into JobCategories values( 'Non-Profit/Volunteering','Youth Development Specialist')

insert into JobCategories values( 'Administrative','Accounts Payable Clerk')
insert into JobCategories values( 'Administrative','Executive Assistant')
insert into JobCategories values( 'Administrative','Program Coordinator')
insert into JobCategories values( 'Administrative','Accounts Receivable Clerk')
insert into JobCategories values( 'Administrative','Executive Director')
insert into JobCategories values( 'Administrative','Program Manager')
insert into JobCategories values( 'Administrative','Administrative Assistant')
insert into JobCategories values( 'Administrative','File Clerk')
insert into JobCategories values( 'Administrative','Project Coordinator')
insert into JobCategories values( 'Administrative','Assistant Manager')
insert into JobCategories values( 'Administrative','Medical Records Clerk')
insert into JobCategories values( 'Administrative','Project Manager')
insert into JobCategories values( 'Administrative','Branch Manager')
insert into JobCategories values( 'Administrative','Office Assistant')
insert into JobCategories values( 'Administrative','Purchasing Agent')
insert into JobCategories values( 'Administrative','Clerk')
insert into JobCategories values( 'Administrative','Office Clerk')
insert into JobCategories values( 'Administrative','Purchasing Manager')
insert into JobCategories values( 'Administrative','Data Entry Operator')
insert into JobCategories values( 'Administrative','Office Manager')
insert into JobCategories values( 'Administrative','Receptionist')
insert into JobCategories values( 'Administrative','Director of Operations')
insert into JobCategories values( 'Administrative','Operations Manager')
insert into JobCategories values( 'Administrative','Receptionist Administrative Assistant')
insert into JobCategories values( 'Administrative','District Manager')
insert into JobCategories values( 'Administrative','Personal Assistant')
insert into JobCategories values( 'Administrative','Secretary')
insert into JobCategories values( 'Administrative','Executive Administrative Assistant')
insert into JobCategories values( 'Administrative','Product Manager')
insert into JobCategories values( 'Administrative','Territory Manager')

insert into JobCategories values( 'Computer/Internet','Application Developer')
insert into JobCategories values( 'Computer/Internet','IT Specialist')
insert into JobCategories values( 'Computer/Internet','Software Engineer')
insert into JobCategories values( 'Computer/Internet','Business Objects Developer')
insert into JobCategories values( 'Computer/Internet','Informatica Developer')
insert into JobCategories values( 'Computer/Internet','System Administrator')
insert into JobCategories values( 'Computer/Internet','Business Systems Analyst')
insert into JobCategories values( 'Computer/Internet','Java Developer')
insert into JobCategories values( 'Computer/Internet','Systems Analyst')
insert into JobCategories values( 'Computer/Internet','Data Analyst')
insert into JobCategories values( 'Computer/Internet','NET Developer')
insert into JobCategories values( 'Computer/Internet','Systems Engineer')
insert into JobCategories values( 'Computer/Internet','Database Administrator')
insert into JobCategories values( 'Computer/Internet','Network Administrator')
insert into JobCategories values( 'Computer/Internet','Technical Support Engineer')
insert into JobCategories values( 'Computer/Internet','Director Of Development')
insert into JobCategories values( 'Computer/Internet','Network Engineer')
insert into JobCategories values( 'Computer/Internet','Technical Support Specialist')
insert into JobCategories values( 'Computer/Internet','Embedded Software Engineer')
insert into JobCategories values( 'Computer/Internet','Network Technician')
insert into JobCategories values( 'Computer/Internet','Unix System Administrator')
insert into JobCategories values( 'Computer/Internet','IT Director')
insert into JobCategories values( 'Computer/Internet','Oracle Database Administrator')
insert into JobCategories values( 'Computer/Internet','Web Designer')
insert into JobCategories values( 'Computer/Internet','IT Manager')
insert into JobCategories values( 'Computer/Internet','Oracle Developer')
insert into JobCategories values( 'Computer/Internet','Web Developer')
insert into JobCategories values( 'Computer/Internet','IT Project Manager')
insert into JobCategories values( 'Computer/Internet','Programmer Analyst')
insert into JobCategories values( 'Computer/Internet','Webmaster')

insert into JobCategories values( 'Pharmaceutical/Bio-tech','Analytical Chemist')
insert into JobCategories values( 'Pharmaceutical/Bio-tech','Lab Technician')
insert into JobCategories values( 'Pharmaceutical/Bio-tech','Pharmacist')
insert into JobCategories values( 'Pharmaceutical/Bio-tech','Lab Assistant')
insert into JobCategories values( 'Pharmaceutical/Bio-tech','Pharmaceutical Sales Representative')
insert into JobCategories values( 'Pharmaceutical/Bio-tech','Pharmacy Technician')

insert into JobCategories values( 'Arts/Entertainment/Publishing','Art Director')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Graphics Designer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Unigraphics Designer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Assistant Editor')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Graphics Designer Production Artist')
insert into JobCategories values( 'Arts/Entertainment/Publishing','User Interface Designer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Designer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Illustrator')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Video Editor')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Editor')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Journalist')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Writer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Editorial Assistant')
insert into JobCategories values( 'Arts/Entertainment/Publishing','News Producer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Writer Editor')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Graphic Artist')
insert into JobCategories values( 'Arts/Entertainment/Publishing','News Reporter')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Zoo Keeper')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Graphic Web Designer')
insert into JobCategories values( 'Arts/Entertainment/Publishing','Photographer')

insert into JobCategories values( 'Hospitality/Travel','Banquet Manager')
insert into JobCategories values( 'Hospitality/Travel','Greeter')
insert into JobCategories values( 'Hospitality/Travel','Kennel Attendant')
insert into JobCategories values( 'Hospitality/Travel','Event Manager')
insert into JobCategories values( 'Hospitality/Travel','Guest Service Agent')
insert into JobCategories values( 'Hospitality/Travel','Kennel Technician')
insert into JobCategories values( 'Hospitality/Travel','Event Planner')
insert into JobCategories values( 'Hospitality/Travel','Housekeeper')
insert into JobCategories values( 'Hospitality/Travel','Travel Agent')
insert into JobCategories values( 'Hospitality/Travel','Floral Designer')
insert into JobCategories values( 'Hospitality/Travel','Kennel Assistant')

insert into JobCategories values( 'Real Estate','Assistant Property Manager')
insert into JobCategories values( 'Real Estate','Leasing Agent')
insert into JobCategories values( 'Real Estate','Real Estate Appraiser')
insert into JobCategories values( 'Real Estate','Land Surveyor')
insert into JobCategories values( 'Real Estate','Leasing Consultant')
insert into JobCategories values( 'Real Estate','Lease Administrator')
insert into JobCategories values( 'Real Estate','Property Manager')

insert into JobCategories values( 'Banking/Loans','Analyst')
insert into JobCategories values( 'Banking/Loans','Investment Analyst')
insert into JobCategories values( 'Banking/Loans','Underwriter')
insert into JobCategories values( 'Banking/Loans','Bank Teller')
insert into JobCategories values( 'Banking/Loans','Loan Consultant')
insert into JobCategories values( 'Banking/Loans','Underwriter Trainee')
insert into JobCategories values( 'Banking/Loans','Banker')
insert into JobCategories values( 'Banking/Loans','Loan Officer')
insert into JobCategories values( 'Banking/Loans','Underwriting Assistant')
insert into JobCategories values( 'Banking/Loans','Credit Analyst')
insert into JobCategories values( 'Banking/Loans','Loan Processor')
insert into JobCategories values( 'Banking/Loans','Universal Banker')
insert into JobCategories values( 'Banking/Loans','Escrow Assistant')
insert into JobCategories values( 'Banking/Loans','Mortgage Loan Officer')
insert into JobCategories values( 'Banking/Loans','In Store Banker')
insert into JobCategories values( 'Banking/Loans','Teller')

insert into JobCategories values( 'Human Resources','Director Of Human Resources')
insert into JobCategories values( 'Human Resources','HR Manager')
insert into JobCategories values( 'Human Resources','Recruiting Coordinator')
insert into JobCategories values( 'Human Resources','Executive Recruiter')
insert into JobCategories values( 'Human Resources','HR Recruiter')
insert into JobCategories values( 'Human Resources','Recruiting Manager')
insert into JobCategories values( 'Human Resources','HR Administrator')
insert into JobCategories values( 'Human Resources','HR Representative')
insert into JobCategories values( 'Human Resources','Technical Recruiter')
insert into JobCategories values( 'Human Resources','HR Consultant')
insert into JobCategories values( 'Human Resources','HR Specialist')
insert into JobCategories values( 'Human Resources','VP of Human Resources')
insert into JobCategories values( 'Human Resources','HR Coordinator')
insert into JobCategories values( 'Human Resources','Job Coach')
insert into JobCategories values( 'Human Resources','HR Generalist')
insert into JobCategories values( 'Human Resources','Recruiter')

insert into JobCategories values( 'Restaurant/Food Service','Baker')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Bath Department Supervisor')
insert into JobCategories values( 'Restaurant/Food Service','Line Cook')
insert into JobCategories values( 'Restaurant/Food Service','Bartender')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Designer')
insert into JobCategories values( 'Restaurant/Food Service','Restaurant Bartender')
insert into JobCategories values( 'Restaurant/Food Service','Cook')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Helper')
insert into JobCategories values( 'Restaurant/Food Service','Restaurant Manager')
insert into JobCategories values( 'Restaurant/Food Service','Dishwasher')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Manager')
insert into JobCategories values( 'Restaurant/Food Service','Restaurant Worker')
insert into JobCategories values( 'Restaurant/Food Service','Executive Chef')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Staff')
insert into JobCategories values( 'Restaurant/Food Service','Sous Chef')
insert into JobCategories values( 'Restaurant/Food Service','Food Service Worker')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Steward')
insert into JobCategories values( 'Restaurant/Food Service','Wait Staff')
insert into JobCategories values( 'Restaurant/Food Service','Grill Cook')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Supervisor')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Assistant')
insert into JobCategories values( 'Restaurant/Food Service','Kitchen Worker')

insert into JobCategories values( 'Construction/Facilities','Carpenter')
insert into JobCategories values( 'Construction/Facilities','Groundskeeper')
insert into JobCategories values( 'Construction/Facilities','Laborer')
insert into JobCategories values( 'Construction/Facilities','Construction Manager')
insert into JobCategories values( 'Construction/Facilities','HVAC Technician')
insert into JobCategories values( 'Construction/Facilities','Maintenance Manager')
insert into JobCategories values( 'Construction/Facilities','Construction Superintendent')
insert into JobCategories values( 'Construction/Facilities','Heavy Equipment Operator')
insert into JobCategories values( 'Construction/Facilities','Maintenance Mechanic')
insert into JobCategories values( 'Construction/Facilities','Construction Worker')
insert into JobCategories values( 'Construction/Facilities','Industrial Designer')
insert into JobCategories values( 'Construction/Facilities','Maintenance Supervisor')
insert into JobCategories values( 'Construction/Facilities','Custodian')
insert into JobCategories values( 'Construction/Facilities','Industrial Electrician')
insert into JobCategories values( 'Construction/Facilities','Maintenance Technician')
insert into JobCategories values( 'Construction/Facilities','Electrician')
insert into JobCategories values( 'Construction/Facilities','Installer')
insert into JobCategories values( 'Construction/Facilities','Maintenance Worker')
insert into JobCategories values( 'Construction/Facilities','Equipment Operator')
insert into JobCategories values( 'Construction/Facilities','Interior Designer')
insert into JobCategories values( 'Construction/Facilities','Painter')
insert into JobCategories values( 'Construction/Facilities','Estimator')
insert into JobCategories values( 'Construction/Facilities','Janitor')
insert into JobCategories values( 'Construction/Facilities','Plant Manager')
insert into JobCategories values( 'Construction/Facilities','Facilities Manager')
insert into JobCategories values( 'Construction/Facilities','Journeyman Electrician')
insert into JobCategories values( 'Construction/Facilities','Welder')
insert into JobCategories values( 'Construction/Facilities','General Maintenance Technician')
insert into JobCategories values( 'Construction/Facilities','Journeyman Lineman')
insert into JobCategories values( 'Construction/Facilities','Welder Fabricator')

insert into JobCategories values( 'Insurance','Benefits Administrator')
insert into JobCategories values( 'Insurance','Fraud Investigator')
insert into JobCategories values( 'Insurance','Investigator')
insert into JobCategories values( 'Insurance','Benefits Manager')
insert into JobCategories values( 'Insurance','Inspector')
insert into JobCategories values( 'Insurance','Lead Asset Protection Associate')
insert into JobCategories values( 'Insurance','Benefits Specialist')
insert into JobCategories values( 'Insurance','Insurance Agent')
insert into JobCategories values( 'Insurance','Field Investigator')
insert into JobCategories values( 'Insurance','Insurance Sales Representative')

insert into JobCategories values( 'Retail','Assistant Store Manager')
insert into JobCategories values( 'Retail','Hair Stylist')
insert into JobCategories values( 'Retail','Retail Sales Representative')
insert into JobCategories values( 'Retail','Buyer')
insert into JobCategories values( 'Retail','Head Cashier')
insert into JobCategories values( 'Retail','Retail Store Manager')
insert into JobCategories values( 'Retail','Buyer Planner')
insert into JobCategories values( 'Retail','Jeweler')
insert into JobCategories values( 'Retail','Sales Assistant')
insert into JobCategories values( 'Retail','Cashier')
insert into JobCategories values( 'Retail','Key Holder')
insert into JobCategories values( 'Retail','Store Manager')
insert into JobCategories values( 'Retail','Esthetician')
insert into JobCategories values( 'Retail','Kitchen Bath Sales Associate')
insert into JobCategories values( 'Retail','Visual Merchandiser')
insert into JobCategories values( 'Retail','Footwear Associate')
insert into JobCategories values( 'Retail','Night Manager')
insert into JobCategories values( 'Retail','Youth Department Sales Manager')
insert into JobCategories values( 'Retail','Garden Sales Associate')
insert into JobCategories values( 'Retail','Representative Retail Sales')
insert into JobCategories values( 'Retail','Grooming Salon Manager')
insert into JobCategories values( 'Retail','Retail Sales Associate')

insert into JobCategories values( 'Customer Service','Branch Customer Service Representative')
insert into JobCategories values( 'Customer Service','Field Service Representative')
insert into JobCategories values( 'Customer Service','Lot Attendent')
insert into JobCategories values( 'Customer Service','Customer Service Advisor')
insert into JobCategories values( 'Customer Service','Field Service Technician')
insert into JobCategories values( 'Customer Service','Relationship Manager')
insert into JobCategories values( 'Customer Service','Customer Service Associate')
insert into JobCategories values( 'Customer Service','Field Technician')
insert into JobCategories values( 'Customer Service','Retail Customer Support Representative')
insert into JobCategories values( 'Customer Service','Customer Service Manager')
insert into JobCategories values( 'Customer Service','Flight Attendant')
insert into JobCategories values( 'Customer Service','Sales Engineer')
insert into JobCategories values( 'Customer Service','Customer Service Representative')
insert into JobCategories values( 'Customer Service','Game Manager')
insert into JobCategories values( 'Customer Service','Service Manager')
insert into JobCategories values( 'Customer Service','Desktop Support')
insert into JobCategories values( 'Customer Service','General Service Technician')
insert into JobCategories values( 'Customer Service','Service Technician')
insert into JobCategories values( 'Customer Service','Desktop Support Technician')
insert into JobCategories values( 'Customer Service','Help Desk Analyst')
insert into JobCategories values( 'Customer Service','Universal Service Representative')
insert into JobCategories values( 'Customer Service','Emergency Road Service Counselor')
insert into JobCategories values( 'Customer Service','Help Desk Specialist')
insert into JobCategories values( 'Customer Service','Valet Attendant')
insert into JobCategories values( 'Customer Service','Field Engineer')
insert into JobCategories values( 'Customer Service','Help Desk Technical Support')
insert into JobCategories values( 'Customer Service','Field Service Engineer')
insert into JobCategories values( 'Customer Service','Help Desk Technician')

insert into JobCategories values( 'Law Enforcement/Security','Criminal Investigator')
insert into JobCategories values( 'Law Enforcement/Security','Loss Prevention Investigator')
insert into JobCategories values( 'Law Enforcement/Security','Security Officer')
insert into JobCategories values( 'Law Enforcement/Security','International Police Officer')
insert into JobCategories values( 'Law Enforcement/Security','Loss Prevention Manager')
insert into JobCategories values( 'Law Enforcement/Security','Transportation Security Officer')
insert into JobCategories values( 'Law Enforcement/Security','Juvenile Detention Officer')
insert into JobCategories values( 'Law Enforcement/Security','Police Officer')
insert into JobCategories values( 'Law Enforcement/Security','Unarmed Security Guard')
insert into JobCategories values( 'Law Enforcement/Security','Juvenile Probation Officer')
insert into JobCategories values( 'Law Enforcement/Security','Security Guard')

insert into JobCategories values( 'Sales','Account Executive')
insert into JobCategories values( 'Sales','Key Account Manager')
insert into JobCategories values( 'Sales','Sales Coordinator')
insert into JobCategories values( 'Sales','Account Manager')
insert into JobCategories values( 'Sales','Merchandiser')
insert into JobCategories values( 'Sales','Sales Executive')
insert into JobCategories values( 'Sales','Account Representative')
insert into JobCategories values( 'Sales','National Account Manager')
insert into JobCategories values( 'Sales','Sales Manager')
insert into JobCategories values( 'Sales','Business Development Manager')
insert into JobCategories values( 'Sales','National Sales Manager')
insert into JobCategories values( 'Sales','Sales Representative')
insert into JobCategories values( 'Sales','Business Development Specialist')
insert into JobCategories values( 'Sales','Outside Sales Representative')
insert into JobCategories values( 'Sales','Sales Specialist')
insert into JobCategories values( 'Sales','Director Of Business Development')
insert into JobCategories values( 'Sales','Regional Sales Manager')
insert into JobCategories values( 'Sales','Telemarketer')
insert into JobCategories values( 'Sales','Director Of Sales')
insert into JobCategories values( 'Sales','Retail Merchandiser')
insert into JobCategories values( 'Sales','Territory Sales Manager')
insert into JobCategories values( 'Sales','District Sales Manager')
insert into JobCategories values( 'Sales','Route Sales Representative')
insert into JobCategories values( 'Sales','Trader')
insert into JobCategories values( 'Sales','Field Representative')
insert into JobCategories values( 'Sales','Sales Associate')
insert into JobCategories values( 'Sales','VP of Sales')
insert into JobCategories values( 'Sales','Inside Sales Representative')
insert into JobCategories values( 'Sales','Sales Consultant')
insert into JobCategories values( 'Sales','Work Sales Representative')

insert into JobCategories values( 'Education/Training','Assistant Teacher')
insert into JobCategories values( 'Education/Training','Kids Activity Assistant')
insert into JobCategories values( 'Education/Training','Trainer')
insert into JobCategories values( 'Education/Training','Counselor')
insert into JobCategories values( 'Education/Training','Kindergarten Teacher')
insert into JobCategories values( 'Education/Training','Training Coordinator')
insert into JobCategories values( 'Education/Training','Enrollment Counselor')
insert into JobCategories values( 'Education/Training','Korean Language Instructor')
insert into JobCategories values( 'Education/Training','Training Manager')
insert into JobCategories values( 'Education/Training','Guidance Counselor')
insert into JobCategories values( 'Education/Training','Nanny')
insert into JobCategories values( 'Education/Training','Training Specialist')
insert into JobCategories values( 'Education/Training','Health Educator')
insert into JobCategories values( 'Education/Training','Teacher')
insert into JobCategories values( 'Education/Training','Yoga Instructor')
insert into JobCategories values( 'Education/Training','Instructional Designer')
insert into JobCategories values( 'Education/Training','Technical Trainer')
insert into JobCategories values( 'Education/Training','Instructor')
insert into JobCategories values( 'Education/Training','Technical Writer')

insert into JobCategories values( 'Legal','Attorney')
insert into JobCategories values( 'Legal','Legal Administrative Assistant')
insert into JobCategories values( 'Legal','Litigation Attorney')
insert into JobCategories values( 'Legal','General Counsel')
insert into JobCategories values( 'Legal','Legal Assistant')
insert into JobCategories values( 'Legal','Litigation Paralegal')
insert into JobCategories values( 'Legal','Judge Advocate')
insert into JobCategories values( 'Legal','Legal Secretary')
insert into JobCategories values( 'Legal','Paralegal')

insert into JobCategories values( 'Telecommunications','Broadband Technician')
insert into JobCategories values( 'Telecommunications','Telecommunications Specialist')
insert into JobCategories values( 'Telecommunications','Wireless Consultant')
insert into JobCategories values( 'Telecommunications','Communications Specialist')
insert into JobCategories values( 'Telecommunications','Telecommunications Technician')
insert into JobCategories values( 'Telecommunications','ZURB Operator')

insert into JobCategories values( 'Engineering/Architecture','Architect')
insert into JobCategories values( 'Engineering/Architecture','GIS Analyst')
insert into JobCategories values( 'Engineering/Architecture','Mechanical Design Engineer')
insert into JobCategories values( 'Engineering/Architecture','Civil Engineer')
insert into JobCategories values( 'Engineering/Architecture','GIS Specialist')
insert into JobCategories values( 'Engineering/Architecture','Mechanical Engineer')
insert into JobCategories values( 'Engineering/Architecture','Design Engineer')
insert into JobCategories values( 'Engineering/Architecture','GIS Technician')
insert into JobCategories values( 'Engineering/Architecture','Operations Research Analyst')
insert into JobCategories values( 'Engineering/Architecture','Electrical Designer')
insert into JobCategories values( 'Engineering/Architecture','General Engineer')
insert into JobCategories values( 'Engineering/Architecture','Optical Engineer')
insert into JobCategories values( 'Engineering/Architecture','Electrical Engineer')
insert into JobCategories values( 'Engineering/Architecture','Geographer')
insert into JobCategories values( 'Engineering/Architecture','Process Engineer')
insert into JobCategories values( 'Engineering/Architecture','Electronics Engineer')
insert into JobCategories values( 'Engineering/Architecture','Geologist')
insert into JobCategories values( 'Engineering/Architecture','Project Engineer')
insert into JobCategories values( 'Engineering/Architecture','Engineer')
insert into JobCategories values( 'Engineering/Architecture','Geotechnical Engineer')
insert into JobCategories values( 'Engineering/Architecture','Scientist')
insert into JobCategories values( 'Engineering/Architecture','Engineering Manager')
insert into JobCategories values( 'Engineering/Architecture','Hardware Design Engineer')
insert into JobCategories values( 'Engineering/Architecture','Test Engineer')
insert into JobCategories values( 'Engineering/Architecture','Engineering Technician')
insert into JobCategories values( 'Engineering/Architecture','Hardware Engineer')
insert into JobCategories values( 'Engineering/Architecture','Ultrasound Technician')
insert into JobCategories values( 'Engineering/Architecture','Environmental Engineer')
insert into JobCategories values( 'Engineering/Architecture','Industrial Engineer')
insert into JobCategories values( 'Engineering/Architecture','VP Of Engineering')

insert into JobCategories values( 'Manufacturing/Mechanical','Assembler')
insert into JobCategories values( 'Manufacturing/Mechanical','Manufacturing Engineer')
insert into JobCategories values( 'Manufacturing/Mechanical','QA Tester')
insert into JobCategories values( 'Manufacturing/Mechanical','Autocad Drafter')
insert into JobCategories values( 'Manufacturing/Mechanical','Material Handler')
insert into JobCategories values( 'Manufacturing/Mechanical','Quality Control Inspector')
insert into JobCategories values( 'Manufacturing/Mechanical','Automotive Technician')
insert into JobCategories values( 'Manufacturing/Mechanical','Operator')
insert into JobCategories values( 'Manufacturing/Mechanical','Quality Engineer')
insert into JobCategories values( 'Manufacturing/Mechanical','CNC Machinist')
insert into JobCategories values( 'Manufacturing/Mechanical','Production Assistant')
insert into JobCategories values( 'Manufacturing/Mechanical','Research Analyst')
insert into JobCategories values( 'Manufacturing/Mechanical','Chemist')
insert into JobCategories values( 'Manufacturing/Mechanical','Production Manager')
insert into JobCategories values( 'Manufacturing/Mechanical','Research Assistant')
insert into JobCategories values( 'Manufacturing/Mechanical','Drafter')
insert into JobCategories values( 'Manufacturing/Mechanical','Production Supervisor')
insert into JobCategories values( 'Manufacturing/Mechanical','Research Associate')
insert into JobCategories values( 'Manufacturing/Mechanical','Electronic Assembler')
insert into JobCategories values( 'Manufacturing/Mechanical','Production Worker')
insert into JobCategories values( 'Manufacturing/Mechanical','Research Scientist')
insert into JobCategories values( 'Manufacturing/Mechanical','Electronics Technician')
insert into JobCategories values( 'Manufacturing/Mechanical','QA Analyst')
insert into JobCategories values( 'Manufacturing/Mechanical','Safety Manager')
insert into JobCategories values( 'Manufacturing/Mechanical','Machine Operator')
insert into JobCategories values( 'Manufacturing/Mechanical','QA Engineer')
insert into JobCategories values( 'Manufacturing/Mechanical','Technician')
insert into JobCategories values( 'Manufacturing/Mechanical','Machinist')
insert into JobCategories values( 'Manufacturing/Mechanical','QA Specialist')
insert into JobCategories values( 'Manufacturing/Mechanical','Test Technician')

insert into JobCategories values( 'Transportation/Logistics','Bus Driver')
insert into JobCategories values( 'Transportation/Logistics','Logistics Coordinator')
insert into JobCategories values( 'Transportation/Logistics','Van Driver')
insert into JobCategories values( 'Transportation/Logistics','Delivery Driver')
insert into JobCategories values( 'Transportation/Logistics','Logistics Manager')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Assistant')
insert into JobCategories values( 'Transportation/Logistics','Diesel Mechanic')
insert into JobCategories values( 'Transportation/Logistics','Nationwide Truck Driver')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Associate')
insert into JobCategories values( 'Transportation/Logistics','Dispatcher')
insert into JobCategories values( 'Transportation/Logistics','Order Builder')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Clerk')
insert into JobCategories values( 'Transportation/Logistics','Driver')
insert into JobCategories values( 'Transportation/Logistics','Receiving Associate')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Driver')
insert into JobCategories values( 'Transportation/Logistics','Driver Merchandiser')
insert into JobCategories values( 'Transportation/Logistics','Receiving Merchandise Pick Up Associate')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Lead')
insert into JobCategories values( 'Transportation/Logistics','Forklift Operator')
insert into JobCategories values( 'Transportation/Logistics','Route Driver')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Manager')
insert into JobCategories values( 'Transportation/Logistics','Freight Team Associate')
insert into JobCategories values( 'Transportation/Logistics','Shipping Clerk')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Specialist')
insert into JobCategories values( 'Transportation/Logistics','Household Driver')
insert into JobCategories values( 'Transportation/Logistics','Transportation Manager')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Supervisor')
insert into JobCategories values( 'Transportation/Logistics','Logistics Analyst')
insert into JobCategories values( 'Transportation/Logistics','Truck Driver')
insert into JobCategories values( 'Transportation/Logistics','Warehouse Worker')

insert into JobCategories values( 'Government/Military','Environmental Scientist')
insert into JobCategories values( 'Government/Military','Lifeguard')
insert into JobCategories values( 'Government/Military','Zoning Manager')
insert into JobCategories values( 'Government/Military','Federal Government Worker')
insert into JobCategories values( 'Government/Military','USAR Unit Administrator')
insert into JobCategories values( 'Government/Military','Zoning Specialist')
insert into JobCategories values( 'Government/Military','Firefighter')
insert into JobCategories values( 'Government/Military','Wildlife Biologist')
insert into JobCategories values( 'Government/Military','Zoning Supervisor')
insert into JobCategories values( 'Government/Military','Grant Writer')
insert into JobCategories values( 'Government/Military','Zipsort Operator')
insert into JobCategories values( 'Government/Military','Intelligence Analyst')
insert into JobCategories values( 'Government/Military','Zoning Enforcement Inspector')

insert into JobCategories values( 'Marketing/Advertising/PR','Brand Manager')
insert into JobCategories values( 'Marketing/Advertising/PR','Marketing Assistant')
insert into JobCategories values( 'Marketing/Advertising/PR','Online Marketing Manager')
insert into JobCategories values( 'Marketing/Advertising/PR','Copywriter')
insert into JobCategories values( 'Marketing/Advertising/PR','Marketing Associate')
insert into JobCategories values( 'Marketing/Advertising/PR','Product Marketing Manager')
insert into JobCategories values( 'Marketing/Advertising/PR','Director Of Communication')
insert into JobCategories values( 'Marketing/Advertising/PR','Marketing Coordinator')
insert into JobCategories values( 'Marketing/Advertising/PR','Public Relations Manager')
insert into JobCategories values( 'Marketing/Advertising/PR','Director Of Marketing')
insert into JobCategories values( 'Marketing/Advertising/PR','Marketing Manager')
insert into JobCategories values( 'Marketing/Advertising/PR','VP of Marketing')
insert into JobCategories values( 'Marketing/Advertising/PR','Market Research Analyst')
insert into JobCategories values( 'Marketing/Advertising/PR','Marketing Specialist')

insert into JobCategories values( 'Upper Management/Consulting','Business Analyst')
insert into JobCategories values( 'Upper Management/Consulting','Business Process Analyst')
insert into JobCategories values( 'Upper Management/Consulting','General Manager')
insert into JobCategories values( 'Upper Management/Consulting','Business Manager')
insert into JobCategories values( 'Upper Management/Consulting','Chief Financial Officer')
insert into JobCategories values( 'Upper Management/Consulting','Manager')
insert into JobCategories values( 'Upper Management/Consulting','Business Office Manager')
insert into JobCategories values( 'Upper Management/Consulting','Director')
insert into JobCategories values( 'Upper Management/Consulting','VP')
